### ISSUE TITLE
Error in attempt to add library to Arduino 1.8.5. 

### ISSUE THREAD

**Issue by restorey** [sparkfun/Papa_Soundie_Audio_Player#5]
I cannot add Papa_Soundie_Audio_Player Library to Arduino IDE. When I try I get an error.
"Specified folder/zip file does not contain a valid library"

Arduino: 1.8.5 (Windows 10), Board: "Arduino Due (Programming Port)"

I am at a loss as to why this error pops up except there must be something wrong with the file.

**Comment by per1234** [comment]
It's only possible to install libraries from a .zip file when the library is in the root of the file but in this case the library is in a subfolder so you can't use that installation technique with the .zip file of the entire repository.

SparkFun has added a .zip file of the library itself to the repository that you can use to install the library via the "Add .ZIP Library" technique:

1. Download https://github.com/sparkfun/Papa_Soundie_Audio_Player/raw/master/Libraries/Arduino/src.zip
2. (In the Arduino IDE) Sketch > Include Library > Add .ZIP Library > select the downloaded file > Open

**Comment by restorey** [comment]
per1234. Thank you for the quick response. Download is now functional.
The problem stemmed from a link in the SparkFun tutorial for the Papa_Soundie_audio_player_hookup_guide.
